# Generated by Django 3.1.4 on 2024-06-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_answer_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
